[build]
command = "npm i --save react@npm:@preact/compat react-dom@npm:@preact/compat ; npm run build"

[[plugins]]
package = "./plugin-prebuild-commands"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[plugins]]
package = "netlify-plugin-cache-nextjs"
